name: constelutions

services:
  marketing-site:
    container_name: marketing-site
    build: .
    ports:
      - "8080:8080"
    networks:
      - constelutions-network

networks:
  constelutions-network:
    name: constelutions-network
